name: Deploy OWASP Juice Shop and Run OWASP ZAP DAST

on:
  #push:
    branches: [ main, master ]
  #pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  actions: write

jobs:
  zap-dast:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    services:
      juice-shop:
        image: bkimminich/juice-shop:latest 
        options: --publish 3000:3000

    steps:
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to be available..."
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop is ready!"

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          format: 'html,json,md'
          report: 'zap_report.html'
          json_report: 'zap_report.json'
          md_report: 'zap_report.md'

      - name: Upload ZAP Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.json
            zap_report.md
